name: Generate Content

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight UTC
  workflow_dispatch:

jobs:
  generate_content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dvdtsb/packages
        uses: actions/checkout@v2
        with:
          repository: dvdtsb/packages
          path: packages

      - name: Checkout dvdtsb/docs
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Python Script
        run: |
          python3 generate_content.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Generated content"
          git push origin main
